### PR TITLE
test: increase the globalTimeout rule values

### PR DESCRIPTION
**Pull request by athakor**
Increase the `globalTimeout ` rules vale to overcome from the timeout issue.

### CODE REVIEW

**Review by pmakani — APPROVED** [review]

**Review by dmitry-fa — CHANGES_REQUESTED** [review]
Increasing timeout will not fix the problem.

**Comment by athakor** [comment]
> Increasing timeout will not fix the problem.

Test working fine as expected but sometime it will take bit more time to executes the things as compare to expected time so it's better to increase globalTimeOut value to prevent this.

**Comment by dmitry-fa** [comment]
Okay, you need to provide some justification why you believe that increasing global timeout will help.

**Review by dmitry-fa — APPROVED** [review]
please add arguments to increasing timeout

**Review by suraj-qlogic — APPROVED** [review]

**Pull request closed without merging**
